# Generated by Django 5.2 on 2025-06-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_approval", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="approved_limit",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="monthly_salary",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="credit_approval.customer",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="date_of_approval",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="emis_paid_on_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.FloatField(help_text="Annual interest rate in percentage"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure",
            field=models.PositiveIntegerField(help_text="Loan tenure in months"),
        ),
    ]
